In [1]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [2]:
client = MongoClient ("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [4]:
db = client['clinica']
colecao = db['atendimentos']

1. Inserir os 50 registros na coleção 'atendimentos'.

In [ ]:
dados = [
{"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

In [7]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c332abf17882460bbf0c3a'), ObjectId('69c332abf17882460bbf0c3b'), ObjectId('69c332abf17882460bbf0c3c'), ObjectId('69c332abf17882460bbf0c3d'), ObjectId('69c332abf17882460bbf0c3e'), ObjectId('69c332abf17882460bbf0c3f'), ObjectId('69c332abf17882460bbf0c40'), ObjectId('69c332abf17882460bbf0c41'), ObjectId('69c332abf17882460bbf0c42'), ObjectId('69c332abf17882460bbf0c43'), ObjectId('69c332abf17882460bbf0c44'), ObjectId('69c332abf17882460bbf0c45'), ObjectId('69c332abf17882460bbf0c46'), ObjectId('69c332abf17882460bbf0c47'), ObjectId('69c332abf17882460bbf0c48'), ObjectId('69c332abf17882460bbf0c49'), ObjectId('69c332abf17882460bbf0c4a'), ObjectId('69c332abf17882460bbf0c4b'), ObjectId('69c332abf17882460bbf0c4c'), ObjectId('69c332abf17882460bbf0c4d'), ObjectId('69c332abf17882460bbf0c4e'), ObjectId('69c332abf17882460bbf0c4f'), ObjectId('69c332abf17882460bbf0c50'), ObjectId('69c332abf17882460bbf0c51'), ObjectId('69c332abf17882460bbf0c52'), ObjectId('69c332abf17882460bbf0c53'), ObjectId('69c332abf17882460bbf0c54'), ObjectId('69c332abf17882460bbf0c55'), ObjectId('69c332abf17882460bbf0c56'), ObjectId('69c332abf17882460bbf0c57'), ObjectId('69c332abf17882460bbf0c58'), ObjectId('69c332abf17882460bbf0c59'), ObjectId('69c332abf17882460bbf0c5a'), ObjectId('69c332abf17882460bbf0c5b'), ObjectId('69c332abf17882460bbf0c5c'), ObjectId('69c332abf17882460bbf0c5d'), ObjectId('69c332abf17882460bbf0c5e'), ObjectId('69c332abf17882460bbf0c5f'), ObjectId('69c332abf17882460bbf0c60'), ObjectId('69c332abf17882460bbf0c61'), ObjectId('69c332abf17882460bbf0c62'), ObjectId('69c332abf17882460bbf0c63'), ObjectId('69c332abf17882460bbf0c64'), ObjectId('69c332abf17882460bbf0c65'), ObjectId('69c332abf17882460bbf0c66'), ObjectId('69c332abf17882460bbf0c67'), ObjectId('69c332abf17882460bbf0c68'), ObjectId('69c332abf17882460bbf0c69'), ObjectId('69c332abf17882460bbf0c6a'), ObjectId('69c332abf17882460bbf0c6b')], acknowledged=True)

2. Consultar atendimentos com valor entre 90 e 200 reais.

In [8]:
dados_mongo = list(colecao.find ({
    'valor': {'$gte' : 90, '$lte' : 200}
}))

display(dados_mongo)

[{'_id': ObjectId('69c332abf17882460bbf0c3a'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c3b'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c3d'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c3e'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c3f'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c40'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c43'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c44'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c45'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c46'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c47'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c4a'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c4b'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c4c'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c4d'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c4f'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c51'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c53'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c54'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c57'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c58'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c59'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c5a'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c5c'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c5d'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c5e'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c60'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c63'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c64'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c65'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c66'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c68'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c6a'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c6b'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

3. Consultar atendimentos das cidades Assis, Ourinhos, Pompeia e Marília.

In [9]:
dados_cidade = list(colecao.find({
    'cidade' : {'$in': ['Ourinhos', 'Assis', 'Pompeia', 'Marilia']}
}))

display (dados_cidade)

[{'_id': ObjectId('69c332abf17882460bbf0c3a'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c3b'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c3c'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c3d'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c3e'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c3f'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c40'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c41'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c42'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c43'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c44'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c45'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c46'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c47'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c48'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c49'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c4a'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c4b'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c4c'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c4d'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c4e'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c4f'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c50'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c51'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c52'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c53'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c54'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c55'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c56'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c57'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c58'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c59'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c5a'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c5b'),
  'tutor': 'Paulo',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt34',
  'servico': 'Banho',
  'valor': 75,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c5c'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c5d'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c5e'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c5f'),
  'tutor': 'Tiago',
  'animal': 'Gato',
  'nome_pet': 'Lili38',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c60'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c61'),
  'tutor': 'Vitor',
  'animal': 'Gato',
  'nome_pet': 'Mia40',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c62'),
  'tutor': 'Wesley',
  'animal': 'Cachorro',
  'nome_pet': 'Thor41',
  'servico': 'Cirurgia',
  'valor': 870,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c63'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c64'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c65'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c66'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c67'),
  'tutor': 'Bruna',
  'animal': 'Cachorro',
  'nome_pet': 'Spike46',
  'servico': 'Banho',
  'valor': 80,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c332abf17882460bbf0c68'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c69'),
  'tutor': 'Dora',
  'animal': 'Cachorro',
  'nome_pet': 'Mel48',
  'servico': 'Exame',
  'valor': 220,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c332abf17882460bbf0c6a'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c332abf17882460bbf0c6b'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

4. Converter os resultados para DataFrame.

In [10]:
df = pd.DataFrame(dados_cidade)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c332abf17882460bbf0c3a,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c332abf17882460bbf0c3b,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c332abf17882460bbf0c3c,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69c332abf17882460bbf0c3d,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69c332abf17882460bbf0c3e,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,69c332abf17882460bbf0c3f,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,69c332abf17882460bbf0c40,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,69c332abf17882460bbf0c41,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,69c332abf17882460bbf0c42,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,69c332abf17882460bbf0c43,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,69c332abf17882460bbf0c44,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,69c332abf17882460bbf0c45,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,69c332abf17882460bbf0c46,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,69c332abf17882460bbf0c47,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,69c332abf17882460bbf0c48,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,69c332abf17882460bbf0c49,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,69c332abf17882460bbf0c4a,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,69c332abf17882460bbf0c4b,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,69c332abf17882460bbf0c4c,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,69c332abf17882460bbf0c4d,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,69c332abf17882460bbf0c4e,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,69c332abf17882460bbf0c4f,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,69c332abf17882460bbf0c50,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,69c332abf17882460bbf0c51,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,69c332abf17882460bbf0c52,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,69c332abf17882460bbf0c53,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,69c332abf17882460bbf0c54,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,69c332abf17882460bbf0c55,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,69c332abf17882460bbf0c56,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,69c332abf17882460bbf0c57,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,69c332abf17882460bbf0c58,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,69c332abf17882460bbf0c59,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,69c332abf17882460bbf0c5a,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,69c332abf17882460bbf0c5b,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,69c332abf17882460bbf0c5c,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,69c332abf17882460bbf0c5d,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,69c332abf17882460bbf0c5e,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,69c332abf17882460bbf0c5f,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro
38,69c332abf17882460bbf0c60,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
39,69c332abf17882460bbf0c61,Vitor,Gato,Mia40,Banho,70,Marilia,2026-03-02,Cartão
40,69c332abf17882460bbf0c62,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
41,69c332abf17882460bbf0c63,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
42,69c332abf17882460bbf0c64,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
43,69c332abf17882460bbf0c65,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
44,69c332abf17882460bbf0c66,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
45,69c332abf17882460bbf0c67,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
46,69c332abf17882460bbf0c68,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
47,69c332abf17882460bbf0c69,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
48,69c332abf17882460bbf0c6a,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
49,69c332abf17882460bbf0c6b,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

5. Verificar valores nulos.

In [11]:
df.isnull().sum()

_id                0
tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

6. Calcular faturamento total.

In [12]:
faturamento = df['valor'].sum()
print("Faturamento total: " , faturamento)

Faturamento total:  8895

7. Calcular faturamento por cidade.

In [ ]:
faturamento_cidade = df.groupby('cidade')['valor'].sum().sort_values(ascending=False)
faturamento_cidade

cidade
Ourinhos    2380
Marilia     2275
Assis       2220
Pompeia     2020
Name: valor, dtype: int64

8. Calcular faturamento por serviço.

In [14]:
faturamento_servico = df.groupby('servico')['valor'].sum().sort_values(ascending=False)
faturamento_servico

servico
Cirurgia     3370
Consulta     2655
Exame        1505
Vacinação     830
Banho         535
Name: valor, dtype: int64

9. Calcular ticket médio geral.

In [32]:
ticket_medio_geral = df['valor'].mean()
print(f"Média do valor das consultas: {ticket_medio_geral: .2f}")

Média do valor das consultas:  177.90

10. Calcular ticket médio por cidade.

In [34]:
ticket_medio_por_cidade = df.groupby('cidade')['valor'].mean().round(2)
print(f"Média do valor das consultas por cidade: { ticket_medio_por_cidade}")

Média do valor das consultas por cidade: cidade
Assis       170.77
Marilia     189.58
Ourinhos    183.08
Pompeia     168.33
Name: valor, dtype: float64

11. Identificar o serviço mais lucrativo.

In [35]:
servico_mais_lucrativo = df.groupby('servico')['valor'].sum().idxmax()
servico_mais_lucrativo

'Cirurgia'

12. Identificar a cidade com maior faturamento.

In [36]:
cidade_maior_faturamento = df['cidade'].value_counts().idxmax()
cidade_maior_faturamento

'Assis'

13. Identificar os 3 maiores atendimentos.

In [ ]:
top_3_atendimentos = df.nlargest(3, 'valor')[['servico', 'valor']]
top_3_atendimentos

     servico  valor
15  Cirurgia    900
40  Cirurgia    870
7   Cirurgia    820

RELATÓRIO

In [37]:
relatorio ={
    'data_geracao' : datetime.now(),
    'faturamento_total': float(faturamento),
    'faturamento_cidade' : faturamento_cidade.to_dict(),
    'faturamento_servico' : faturamento_servico.to_dict(),
    'ticket_medio_geral' : float(),
    'ticket_medio_por_cidade' :ticket_medio_por_cidade.to_dict(),
    'servico_mais_lucrativo' : servico_mais_lucrativo,
    'cidade_maior_faturamento' :  cidade_maior_faturamento,
    'top_3_atendimentos' : top_3_atendimentos
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 1, 46, 1, 350053),
 'faturamento_total': 8895.0,
 'faturamento_cidade': {'Ourinhos': 2380,
  'Marilia': 2275,
  'Assis': 2220,
  'Pompeia': 2020},
 'faturamento_servico': {'Cirurgia': 3370,
  'Consulta': 2655,
  'Exame': 1505,
  'Vacinação': 830,
  'Banho': 535},
 'ticket_medio_geral': 0.0,
 'ticket_medio_por_cidade': {'Assis': 170.77,
  'Marilia': 189.58,
  'Ourinhos': 183.08,
  'Pompeia': 168.33},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Assis',
 'top_3_atendimentos':      servico  valor
 15  Cirurgia    900
 40  Cirurgia    870
 7   Cirurgia    820}

In [38]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InvalidDocument: Invalid document: cannot encode object:      servico  valor
15  Cirurgia    900
40  Cirurgia    870
7   Cirurgia    820, of type: <class 'pandas.DataFrame'>

In [39]:
for r in colecao_relatorios.find():
    display(r)